export enum Routes {
  HomePage = 'HomePage',
  HomeMessages = 'HomeMessages',
  AskAi = 'AskAi',
  AboutUs = 'AboutUs',
  Account = 'Account',
  Appearance = 'Appearance',
  DataStorage = 'DataStorage',
  FriendifyPremium = 'FriendifyPremium',
  Guideline = 'Guideline',
  HelpSupport = 'HelpSupport',
  Language = 'Language',
  Notifications = 'Notifications',
  PrivateSecurity = 'PrivateSecurity',
  EditProfile = 'EditProfile',
  ConversationData = 'ConversationData',
  MediaManager = 'MediaManager',
  Setting = 'Setting',
  Playground = 'Playground',
  DrawerStack = 'DrawerStack',
  Contacts = 'Contacts',
  FriendifyAi = 'FriendifyAi',
  MyCloud = 'MyCloud',
  ChangeEmail = 'ChangeEmail',
  ChangePassword = 'ChangePassword',
  LinkAccount = 'LinkAccount',
  DeleteAccount = 'DeleteAccount',
  RequestReceieved = 'RequestReceieved',
  AccountRemoved = 'AccountRemoved',

  ChatGroupUser = 'ChatGroupUser',
  ChatOneUser = 'ChatOneUser',
  ProfileGroup = 'ProfileGroup',
  ProfileUser = 'ProfileUser',

  QrCodeProfile = 'QrCodeProfile',
  QrCodeScan = 'QrCodeScan',
  FriendsRequest = 'FriendsRequest',
  InviteFriends = 'InviteFriends',
  SearchResult = 'SearchResult',

  ViewMedia = 'ViewMedia',
  Diamonds = 'Diamonds',
}
